context:
  version: "0.3.0"
  python_min: 3.10.0

package:
  name: einx
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/e/einx/einx-${{ version }}.tar.gz
  sha256: 17ff87c6a0f68ab358c1da489f00e95f1de106fd12ff17d0fb3e210aaa1e5f8c

build:
  number: 0
  noarch: python 
  script: python -m pip install . -vv --no-deps --no-build-isolation 

requirements:
  host:
    - pip
    - python ${{ python_min }}
    - setuptools
    - wheel
  run:
    - python >=${{ python_min }}
    - numpy
    - sympy
    - frozendict

tests:
  - python:
      imports:
        - einx
      pip_check: true

about:
  homepage: https://github.com/fferflo/einx
  license: MIT
  license_file: LICENSE
  summary: Universal Tensor Operations in Einstein-Inspired Notation for Python
  description: |
    einx is a Python library that provides a universal interface to formulate tensor operations in frameworks such as Numpy, PyTorch, Jax and Tensorflow.
  documentation: https://einx.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - iamthebot
