context:
  version: "0.4.0"
  python_min: 3.10.0

package:
  name: einx
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/e/einx/einx-${{ version }}.tar.gz
  sha256: 63705ca3652fb3ab5d481adf3fb49252b234c26d7d25f79dd3d4b49253b40a64

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
    - wheel
  run:
    - python >=${{ python_min }}
    - numpy
    - sympy
    - frozendict

tests:
  - python:
      imports:
        - einx
      pip_check: true

about:
  homepage: https://github.com/fferflo/einx
  license: MIT
  license_file: LICENSE
  summary: Universal Tensor Operations in Einstein-Inspired Notation for Python
  description: |
    einx is a Python library that provides a universal interface to formulate tensor operations in frameworks such as Numpy, PyTorch, Jax and Tensorflow.
  documentation: https://einx.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - iamthebot
